In [3]:
from sklearn.cluster import KMeans
import numpy as np
from sklearn.datasets import make_blobs 

In [6]:
X,y = make_blobs(n_samples=100, centers=3, cluster_std=0.60, random_state=0)
k = 5
kmeans = KMeans(n_clusters=k, random_state=42)
y_pred = kmeans.fit_predict(X)


In [7]:
y_pred

array([4, 1, 4, 1, 1, 1, 2, 2, 4, 1, 3, 3, 4, 3, 2, 4, 2, 1, 2, 2, 2, 2,
       2, 1, 0, 0, 0, 0, 2, 2, 3, 4, 0, 3, 2, 1, 3, 0, 0, 2, 2, 4, 0, 1,
       3, 1, 0, 0, 2, 2, 1, 0, 1, 0, 2, 2, 4, 0, 3, 4, 0, 2, 2, 2, 2, 0,
       3, 2, 0, 3, 2, 3, 1, 4, 0, 3, 3, 1, 2, 4, 1, 3, 0, 1, 0, 3, 3, 1,
       4, 1, 0, 4, 2, 2, 2, 2, 3, 3, 2, 2], dtype=int32)

In [8]:
kmeans.cluster_centers_

array([[ 1.75474522,  1.36799537],
       [ 0.30398964,  4.10772221],
       [-1.65213203,  2.85383679],
       [ 1.38244274,  4.33708655],
       [ 2.64563691,  0.86570712]])

In [9]:
import numpy as np
X_new = np.array([[0,2], [3,2],[5,6]])
kmeans.predict(X_new)

array([2, 4, 3], dtype=int32)

In [10]:
kmeans.transform(X_new).round(2)

array([[1.87, 2.13, 1.86, 2.72, 2.88],
       [1.4 , 3.42, 4.73, 2.84, 1.19],
       [5.66, 5.06, 7.36, 3.98, 5.65]])